version: '3.8'

services:
  mongodb:
    image: mongo:7.0.2
    container_name: nestjs-mongo_db
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongo_data_container:/data/mongodb

volumes:
  mongo_data_container: